# Site settings
title: Maitê Balhester
email: maitebalhester@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   This is Maitê Balhester's personal page, where she writes about technology,
   feminism and life in general.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maiteb.github.io" # the base hostname & protocol for your site
twitter_username: mbalhester
github_username:  maiteb

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

disqus: true
disqus_shortname: 'mbalhester'

# Build settings
markdown: kramdown
